#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso ./solverBC
wclean ./solver
wclean RDE

# ----------------------------------------------------------------- end-of-file
