#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

module purge
module load intel/2019 parallel/mpi.intel.broadwell/2019 compilers/intel/2019


wmake libso ./solverBC
wmake ./solver
wmake ./solverARRAYboost